// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// For prisma generate, DATABASE_URL is not required - only schema file is needed
// This fallback allows generate to work even when DATABASE_URL is not set
// We use process.env directly to avoid errors when DATABASE_URL is not available
const getDatabaseUrl = () => {
  // Use process.env directly (available during build on Vercel)
  // If not available, use a dummy URL (prisma generate doesn't need a real connection)
  return process.env.DATABASE_URL || "postgresql://user:password@localhost:5432/db?schema=public";
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
